name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run hybrid tests (headless)
        env:
          BROWSER: chrome
          HEADLESS: "1"
        run: pytest Tests/test_login.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: Hybrid_Agile_Framework/results/*
